<?php

require_once dirname(__FILE__) . '/../../lib/HTMLCollection.php';

/**
 * Test class for HTMLCollection.
 * Generated by PHPUnit on 2013-03-18 at 08:23:36.
 */
class HTMLCollectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testAdd().
     */
    public function testAdd() {

        $this->object->add('greg');
        $this->assertEquals(count($this->object->getAll()), 1);

        $obj = new stdClass();
        $obj->foo = 'bar';

        // check `add` with `key`
        $this->object->add($obj, 'obj');

        $this->assertEquals(count($this->object->getAll()), 2);

        $this->assertEquals($this->object->get(0), 'greg');
    }

    /**
     * 
     */
    public function testRemove() {
        $this->object->add('greg');
        $this->object->add(new stdClass);
        $this->assertEquals(count($this->object->getAll()), 2);

        $this->object->remove(0);
        $this->assertEquals(count($this->object->getAll()), 1);
    }

    /**
     * 
     */
    public function testExists() {
        $this->object->add(new stdClass(), 'obj');

        $this->assertTrue($this->object->exists('obj'));
    }

}

?>
