<?php

require_once dirname(__FILE__) . '/../../lib/HTMLElement.php';

/**
 * Test class for HTMLElement.
 * Generated by PHPUnit on 2013-03-17 at 19:32:13.
 */
class HTMLElementTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLElement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLElement;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetHtml().
     */
    public function testGetHtml() {
        // check set
        $this->object->setHtml('<h1>test</h1>');

        // check get
        $this->assertEquals('<h1>test</h1>', $this->object->getHtml());
    }

    /**
     * @todo Implement testGetCss().
     */
    public function testGetCss() {
        // check set
        $this->object->setCss('body{color:green;}');

        // check get
        $this->assertEquals('body{color:green;}', $this->object->getCss());
    }

    /**
     * @todo Implement testGetJavascript().
     */
    public function testGetJavascript() {
        // check set
        $this->object->setJavascript('alert(1);');

        // check get
        $this->assertEquals('alert(1);', $this->object->getJavascript());
    }

}

?>
