<?php

require_once dirname(__FILE__) . '/../../../lib/HTMLCollection/Application.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-18 at 13:53:17.
 */
class ApplicationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application
     */
    protected $object;

    protected $originalRequestUri;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        // define the SERVER var - emulating web request
        $docRoot = file_exists('/xampp/htdocs') ? '/xampp/htdocs' : (
                file_exists('/gri/xampp/htdocs') ? '/gri/xampp/htdocs' : 'c:\\'
                );
        $_SERVER = array(
            'REQUEST_URI' => '/gritm',
            'DOCUMENT_ROOT' => $docRoot
        );
        $this->object = new Application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Application::disableLayout
     * @covers Application::getHtml
     */
    public function testDisableLayout() {
        
        $html = $this->object->run(true);
        $this->assertStringStartsWith('<!DOCTYPE', $html);
        $this->assertStringEndsWith('</html>', $html);
        
        $this->object->disableLayout();
        $html = $this->object->run(true);
        $this->assertStringStartsNotWith('<!DOCTYPE', $html);
        $this->assertStringEndsNotWith('</html>', $html);
    }

}
