<?php

require_once dirname(__FILE__) . '/../../../lib/HTMLCollection/Application.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-18 at 14:08:19.
 */
class PageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Page
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

        // define the SERVER var - emulating web request
        $docRoot = file_exists('/xampp/htdocs') ? '/xampp/htdocs' : (
                file_exists('/gri/xampp/htdocs') ? '/gri/xampp/htdocs' : 'c:\\'
                );
        $GLOBALS['_SERVER'] = array(
            'REQUEST_URI' => '/gritm',
            'DOCUMENT_ROOT' => $docRoot
        );

        $this->object = new Page('TestPage', 'test-page');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Page::isResponsibleFor
     * @todo   Implement testIsResponsibleFor().
     */
    public function testIsResponsibleFor() {
        $GLOBALS['_SERVER']['REQUEST_URI'] = '/gritm';
        $this->assertFalse($this->object->isResponsibleFor(new Request));

        $GLOBALS['_SERVER']['REQUEST_URI'] = '/gritm/test-page';
        $this->assertTrue($this->object->isResponsibleFor(new Request));

        $GLOBALS['_SERVER']['REQUEST_URI'] = '/gritm/test-page/add-somthing';
        $this->assertTrue($this->object->isResponsibleFor(new Request));
    }

    /**
     * @covers Page::getHtml
     * @todo   Implement testGetHtml().
     */
    public function testGetHtml() {

        // Remove the following lines when you implement this test.
        $html = $this->object->getHtml();

        // check that the header exists
        $this->assertRegExp('%<h\d+>TestPage</h\d+>%i', $html);
    }

}
