<?php

require_once dirname(__FILE__) . '/../../../../lib/HTMLElement/Button/Add.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-19 at 17:18:52.
 */
class Button_AddTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Button_Add
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Button_Add();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Button_Add::getHtml
     * @todo   Implement testGetHtml().
     */
    public function testGetHtml() {
        
        // Remove the following lines when you implement this test.
        $this->assertNotEmpty($this->object->getHtml());
    }

}
